version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      expo-compatible-dependencies:
        patterns:
          - "expo*"
          - "@expo/*"
          - "react*"
          - "@react-native*"
